#version of docker compose
version: '3'
services:
  ipfshost:
    image: ipfs/kubo:latest
    container_name: ipfs
    env_file:
      - .env
    ports:
      - 4001:4001
      - 4001:4001/udp
      - 8081:8080
      - 5001:5001
    volumes:
      - ./ipfs_staging:/export
      - ./ipfs_data:/data/ipfs
      - ./config:/data/ipfs/config
volumes:
  ipfs_staging:
    external: true
  ipfs_data:
    external: true
